# Change baseurl before deploy
baseurl = "https://har-w.github.io/salon-sparkle/"
# baseurl = "/"
languageCode = "zh-cn"
title = "火花驿站"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "salon-sparkle"

[pagination]
pagerSize = 5